#!/bin/bash -e

# Initialise the LDAP database if it doesn't exists.
#
# Assuming we are running Debian Jessie, it uses OpenLDAP's MDB
if [ ! -f /var/lib/ldap/data.mdb ]; then
   echo "Copying additional schema"
   cp /totaloffice/schema/* /etc/ldap/schema

   # Preseed debconf values
   echo "slapd slapd/no_configuration boolean  true" | debconf-set-selections
   echo "slapd slapd/internal/adminpw password ${LDAP_PASS}" | debconf-set-selections
   echo "slapd slapd/password1 password ${LDAP_PASS}" | debconf-set-selections
   echo "slapd slapd/password2 password ${LDAP_PASS}" | debconf-set-selections
   echo "slapd slapd/domain string ${TODOMAIN}" | debconf-set-selections
   echo "slapd shared/organization string ${ORGANIZATION}" | debconf-set-selections
   # Run reconfigure to set the new values
   dpkg-reconfigure --priority="critical" slapd

   # Star the database and initialise with TotalOffice entries.
   pushd /totaloffice/toconfigure
   echo "Creating default entries"
   ulimit -n 1024 && /usr/sbin/slapd -h "ldap:/// ldapi:///" -g openldap -u openldap -F /etc/ldap/slapd.d
   ./configure.d/20-slapd;
   killall slapd
   popd
fi


echo "Starting slapd..."
# We use ulimit to ensure slapd doesn't runaway with memory.
# https://github.com/docker/docker/issues/4717
ulimit -n 1024 && /usr/sbin/slapd -h "ldap:/// ldapi:///" -g openldap -u openldap -F /etc/ldap/slapd.d -d stats
